import type { BonusStats, Character } from "./types"

const bonusStats: BonusStats = {
  atkFlat: 350,
  hpFlat: 4560,
  defFlat: 0,
  atk: 0.172,
  hp: 0,
  def: 0,
  er: 0.2,
  crit: 0.405 + 0.36,
  critDmg: 0.81 + 0.44,
  basic: 0.172,
  heavy: 0,
  skill: 0,
  liberation: 0,
  /* Element */
  aero: 0,
  electro: 0,
  fusion: 0.6,
  glacio: 0,
  havoc: 0,
  spectro: 0,
}

const team: Record<string, Character> = {
  encore: {
    name: "Encore",
    sequence: 0,
    weapon: {
      name: "Stringmaster",
      rank: 1,
      atk: 40,
      mainStat: "Crit. Rate",
      mainStatAmount: 0.8,
    },
    echo: "Inferno Rider",
    echoSet: ["Molten Rift"],
    build: "43311 Ele/Ele",
    element: "fusion",
    maxForte: 100,
    maxForte2: 0,
    /* stats */
    atk: 34,
    def: 102,
    hp: 841 * 12.5,
    crit: 0.05,
    critDmg: 1.5,
    bonusStats,
    dCond: {
      Forte: 0,
      Forte2: 0,
      Concerto: 0,
      Resonance: 150,
    },
  },
  sanhua: {
    name: "Sanhua",
    sequence: 0,
    weapon: {
      name: "Emerald of Genesis",
      rank: 1,
      atk: 47,
      mainStat: "Crit. Rate",
      mainStatAmount: 0.54,
    },
    echo: "Impermanence Heron",
    echoSet: ["Moonlit Clouds"],
    build: "43311 Ele/Ele",
    element: "glacio",
    maxForte: 100,
    maxForte2: 0,
    /* stats */
    atk: 22,
    def: 77,
    hp: 805 * 12.5,
    crit: 0.05,
    critDmg: 1.5 + 0.44,
    bonusStats: {
      atkFlat: 350,
      hpFlat: 4560,
      defFlat: 0,
      atk: 0.172,
      hp: 0,
      def: 0,
      er: 0.2,
      crit: 0.405 + 0.243,
      critDmg: 0.81 + 0.44,
      basic: 0,
      heavy: 0,
      skill: 0.172,
      liberation: 0,
      /* Element */
      aero: 0,
      electro: 0,
      fusion: 0,
      glacio: 0.6,
      havoc: 0,
      spectro: 0,
    },
    dCond: {
      Forte: 0,
      Forte2: 0,
      Concerto: 0,
      Resonance: 150,
    },
  },
}

export default team
