import type { CharacterSkills } from "./types"

const skills: CharacterSkills = {
  encore: {
    intro: {
      1: {
        name: "Woolies Can Help!",
        category: "Intro",
        classifications: ["fusion", "intro"],
        mv: 1,
        frames: 92,
        hits: 1,
        concerto: 10,
        resonance: 10,
      },
    },
    outro: {
      1: {
        name: "Thermal Field",
        category: "Outro",
        classifications: ["fusion", "outro"],
        mv: 7.0704,
        frames: 0,
        hits: 4,
        concerto: 0,
        resonance: 0,
      },
    },
    basic: {
      1: {
        name: "Woolies Attack 1",
        category: "Basic",
        classifications: ["fusion", "basic"],
        mv: 0.28,
        frames: 30,
        hits: 1,
        concerto: 2.66,
        resonance: 1.32,
      },
      2: {
        name: "Woolies Attack 2",
        category: "Basic",
        classifications: ["fusion", "basic"],
        mv: 0.333,
        frames: 30,
        hits: 1,
        concerto: 2.5,
        resonance: 1.23,
      },
      3: {
        name: "Woolies Attack 3",
        category: "Basic",
        classifications: ["fusion", "basic"],
        mv: 0.667,
        frames: 30,
        hits: 2,
        concerto: 3.32,
        resonance: 1.66,
      },
      4: {
        name: "Woolies Attack 4",
        category: "Basic",
        classifications: ["fusion", "basic"],
        mv: 0.77,
        frames: 30,
        hits: 4,
        concerto: 3.84,
        resonance: 1.92,
      },
      5: {
        name: "Woolies Attack 5",
        category: "Basic",
        classifications: ["fusion", "basic"],
        mv: 1.2,
        frames: 90,
        hits: 1,
        concerto: 6,
        resonance: 3,
      },
      6: {
        name: "Cosmos - Frolicking 1",
        category: "Basic",
        classifications: ["fusion", "basic"],
        mv: 0.9072,
        frames: 20,
        hits: 2,
        concerto: 2.66,
        resonance: 1.32,
      },
      7: {
        name: "Cosmos - Frolicking 2",
        category: "Basic",
        classifications: ["fusion", "basic"],
        mv: 0.8511,
        frames: 40,
        hits: 3,
        concerto: 2.5,
        resonance: 1.23,
      },
      8: {
        name: "Cosmos - Frolicking 3",
        category: "Basic",
        classifications: ["fusion", "basic"],
        mv: 1.3276,
        frames: 30,
        hits: 4,
        concerto: 3.88,
        resonance: 1.92,
      },
      9: {
        name: "Cosmos - Frolicking 4",
        category: "Basic",
        classifications: ["fusion", "basic"],
        mv: 2.9277,
        frames: 90,
        hits: 3,
        concerto: 8.58,
        resonance: 4.29,
      },
    },
    heavy: {
      1: {
        name: "none",
        category: "Heavy",
        classifications: ["fusion", "heavy"],
        mv: 0,
        frames: 0,
        hits: 0,
        concerto: 0,
        resonance: 0,
      },
    },
    skill: {
      1: {
        name: "Flaming Woolies",
        category: "Skill",
        classifications: ["fusion", "skill"],
        mv: 1.706,
        frames: 108,
        cooldown: 10,
        hits: 8,
        concerto: 15,
        resonance: 15.25,
      },
      2: {
        name: "Energetic Welcome",
        category: "Skill",
        classifications: ["fusion", "skill"],
        mv: 1.81,
        frames: 60,
        cooldown: 0,
        hits: 1,
        concerto: 5,
        resonance: 0.75,
      },
      3: {
        name: "Cosmos Rampage",
        category: "Skill",
        classifications: ["fusion", "skill"],
        mv: 1.274,
        frames: 30,
        cooldown: 4,
        hits: 1,
        concerto: 18,
        resonance: 6.56,
      },
    },
    liberation: {
      1: {
        name: "Cosmos Rave",
        category: "Liberation",
        classifications: ["fusion", "liberation"],
        mv: 0,
        frames: 0,
        freezetime: 0,
        cooldown: 16,
        hits: 0,
        concerto: 0,
        resonance: 0,
      },
    },
    forte: {
      1: {
        name: "Cloudy Frenzy",
        category: "Forte",
        classifications: ["fusion", "liberation"],
        mv: 1.68,
        frames: 202,
        hits: 1,
        concerto: 10,
        resonance: 10,
      },
      2: {
        name: "Cosmos Rupture",
        category: "Forte",
        classifications: ["fusion", "liberation"],
        mv: 3.8918,
        frames: 202,
        hits: 1,
        concerto: 10,
        resonance: 10,
      },
    },
  },
  sanhua: {
    intro: {
      1: {
        name: "Freezing Thorns",
        category: "Intro",
        classifications: ["glacio", "intro"],
        mv: 0.7,
        frames: 60,
        hits: 1,
        concerto: 10,
        resonance: 10,
      },
    },
    outro: {
      1: {
        name: "Silversnow",
        category: "Outro",
        classifications: ["glacio", "outro"],
        mv: 0,
        frames: 0,
        hits: 0,
        concerto: 0,
        resonance: 0,
      },
    },
    basic: {
      1: {
        name: "Frigid Light 1",
        category: "Basic",
        classifications: ["glacio", "basic"],
        mv: 0.371,
        frames: 21,
        hits: 1,
        concerto: 2,
        resonance: 0.87,
      },
      2: {
        name: "Frigid Light 2",
        category: "Basic",
        classifications: ["glacio", "basic"],
        mv: 0.245,
        frames: 32,
        hits: 1,
        concerto: 4,
        resonance: 1.32,
      },
      3: {
        name: "Frigid Light 3",
        category: "Basic",
        classifications: ["glacio", "basic"],
        mv: 0.434,
        frames: 42,
        hits: 4,
        concerto: 8,
        resonance: 1.52,
      },
      4: {
        name: "Frigid Light 4",
        category: "Basic",
        classifications: ["glacio", "basic"],
        mv: 0.399,
        frames: 34,
        hits: 2,
        concerto: 8,
        resonance: 1.42,
      },
      5: {
        name: "Frigid Light 5",
        category: "Basic",
        classifications: ["glacio", "basic"],
        mv: 1.176,
        frames: 108,
        hits: 1,
        concerto: 10,
        resonance: 4.2,
      },
    },
    heavy: {
      1: {
        name: "Frigid Light",
        category: "Heavy",
        classifications: ["glacio", "heavy"],
        mv: 0.56,
        frames: 60,
        hits: 1,
        concerto: 8,
        resonance: 2,
      },
    },
    skill: {
      1: {
        name: "Eternal Frost",
        category: "Skill",
        classifications: ["glacio", "skill"],
        mv: 1.81,
        frames: 65,
        cooldown: 10,
        hits: 1,
        concerto: 15,
        resonance: 10,
      },
    },
    liberation: {
      1: {
        name: "Glacial Gaze",
        category: "Liberation",
        classifications: ["glacio", "liberation"],
        mv: 4.0716,
        frames: 94,
        freezetime: 84,
        cooldown: 10,
        hits: 1,
        concerto: 20,
        resonance: 0,
      },
    },
    forte: {
      1: {
        name: "Detonate",
        category: "Forte",
        classifications: ["glacio", "skill"],
        mv: 1.874,
        frames: 92,
        hits: 1,
        concerto: 15 + 2,
        resonance: 0.87,
      },
    },
  },
}

export default skills
