import type { CharacterSkills } from "./types"

const skills: CharacterSkills = {
  sanhua: {
    intro: {
      1: {
        name: "Freezing Thorns",
        classifications: ["glacio", "intro"],
        mv: 0.7,
        frames: 60,
        hits: 1,
        forte: 0,
        concerto: 10,
        resonance: 10,
      },
    },
    outro: {
      1: {
        name: "Silversnow",
        classifications: ["glacio", "outro"],
        mv: 0,
        frames: 0,
        hits: 0,
        forte: 0,
        concerto: 0,
        resonance: 0,
      },
    },
    basic: {
      1: {
        name: "Frigid Light 1",
        classifications: ["glacio", "basic"],
        mv: 0.371,
        frames: 21,
        hits: 1,
        forte: 0,
        concerto: 2,
        resonance: 0.87,
      },
      2: {
        name: "Frigid Light 2",
        classifications: ["glacio", "basic"],
        mv: 0.245,
        frames: 32,
        hits: 1,
        forte: 0,
        concerto: 4,
        resonance: 1.32,
      },
      3: {
        name: "Frigid Light 3",
        classifications: ["glacio", "basic"],
        mv: 0.434,
        frames: 42,
        hits: 4,
        forte: 0,
        concerto: 8,
        resonance: 1.52,
      },
      4: {
        name: "Frigid Light 4",
        classifications: ["glacio", "basic"],
        mv: 0.399,
        frames: 34,
        hits: 2,
        forte: 0,
        concerto: 8,
        resonance: 1.42,
      },
      5: {
        name: "Frigid Light 5",
        classifications: ["glacio", "basic"],
        mv: 1.176,
        frames: 108,
        hits: 1,
        forte: 0,
        concerto: 10,
        resonance: 4.2,
      },
    },
    heavy: {
      1: {
        name: "Frigid Light",
        classifications: ["glacio", "heavy"],
        mv: 0.56,
        frames: 60,
        hits: 1,
        forte: 0,
        concerto: 8,
        resonance: 2,
      },
    },
    skill: {
      1: {
        name: "Eternal Frost",
        classifications: ["glacio", "skill"],
        mv: 1.81,
        frames: 65,
        cooldown: 10,
        hits: 1,
        forte: 0,
        concerto: 15,
        resonance: 10,
      },
    },
    liberation: {
      1: {
        name: "Glacial Gaze",
        classifications: ["glacio", "liberation"],
        mv: 4.0716,
        frames: 94,
        freezetime: 84,
        cooldown: 10,
        hits: 1,
        forte: 0,
        concerto: 20,
        resonance: 0,
      },
    },
    forte: {
      1: {
        name: "Detonate",
        classifications: ["glacio", "heavy"],
        mv: 1.874,
        frames: 92,
        hits: 1,
        forte: 0,
        concerto: 2,
        resonance: 0.87,
      },
    },
  },
}

export default skills
