import type { BuffDefinition } from "@/shared/types"

const encoreBuffs: BuffDefinition[] = [
  {
    id: "Angry Cosmos",
    name: "Angry Cosmos",
    source: "encore",
    trigger: [{ ability: "Cosmos Rave" }],
    appliesTo: "encore",
    modifiers: [{ class: "all", value: 0.1 }],
    duration: 10,
  },
  {
    id: "Woolies Cheer Dance",
    name: "Woolies Cheer Dance",
    source: "encore",
    trigger: [{ ability: "Flaming Woolies" }, { ability: "Cosmos Rampage" }],
    appliesTo: "encore",
    modifiers: [{ class: "fusion", value: 0.1 }],
    duration: 10,
  },
  {
    id: "Cosmos Rave",
    name: "Cosmos Rave",
    source: "encore",
    trigger: [{ ability: "Cosmos Rave" }],
    appliesTo: "encore",
    duration: 10,
  },
  {
    id: "Wooly's Fairy Tale",
    name: "Wooly's Fairy Tale",
    source: "encore",
    trigger: [{ category: "basic" }],
    appliesTo: "encore",
    modifiers: [{ class: "fusion", value: 0.03 }],
    stackLimit: 4,
    sequenceReq: 1,
    duration: 6,
  },
  {
    id: "Sheep-counting Lullaby",
    name: "Sheep-counting Lullaby",
    source: "encore",
    trigger: [{ category: "basic" }],
    appliesTo: "encore",
    modifiers: [{ class: "resonance", value: 10 }],
    cooldown: 10,
    sequenceReq: 2,
    duration: 0,
  },
  {
    id: "Fog? The Black Shores!",
    name: "Fog? The Black Shores!",
    source: "encore",
    trigger: [{ ability: "Cloudy Frenzy" }, { ability: "Cosmos Rupture" }],
    appliesTo: "encore",
    modifiers: [{ class: "multiplier", value: 0.4 }],
    sequenceReq: 3,
    duration: 4,
  },
  {
    id: "Adventure? Let's go!",
    name: "Adventure? Let's go!",
    source: "encore",
    trigger: [{ ability: "Cosmos Rupture" }],
    appliesTo: "all",
    modifiers: [{ class: "fusion", value: 0.2 }],
    sequenceReq: 4,
    duration: 30,
  },
  {
    id: "Hero Takes the Stage!",
    name: "Hero Takes the Stage!",
    source: "encore",
    appliesTo: "encore",
    modifiers: [{ class: "skill", value: 0.35 }],
    sequenceReq: 5,
    duration: 99999,
  },
  {
    id: "Woolies Save the World!",
    name: "Woolies Save the World!",
    source: "encore",
    trigger: [{ ability: "all", condition: "Cosmos Rave" }],
    appliesTo: "encore",
    modifiers: [{ class: "atk", value: 0.05 }],
    stackLimit: 5,
    stackInterval: 0,
    sequenceReq: 6,
    duration: 10,
  },
]

export default encoreBuffs
