import type { BuffDefinition } from "@/shared/types"

const sanhua: BuffDefinition[] = [
  {
    id: "Condensation",
    name: "Condensation",
    source: "sanhua",
    trigger: { category: ["intro"] },
    appliesTo: "sanhua",
    modifiers: [{ class: "skill", value: 0.2 }],
    duration: 8,
  },
  {
    id: "Avalanche",
    name: "Avalanche",
    source: "sanhua",
    trigger: { ability: ["Frigid Light 5"] },
    appliesTo: "sanhua",
    modifiers: [],
    duration: 8,
  },
  {
    id: "Avalanche (bonus)",
    name: "Avalanche (bonus)",
    source: "sanhua",
    trigger: {
      ability: ["Detonate"],
      condition: ["Avalanche"],
    },
    appliesTo: "sanhua",
    modifiers: [{ class: "bonus", value: 0.2 }],
    duration: 0.5,
  },
  {
    id: "Silversnow",
    name: "Silversnow",
    source: "sanhua",
    trigger: { ability: ["Silversnow"] },
    appliesTo: "next",
    modifiers: [{ class: "baDeep", value: 0.38 }],
    duration: 14,
  },
  {
    id: "Ice Prism",
    name: "Ice Prism",
    source: "sanhua",
    classifications: ["glacio", "skill"],
    trigger: { ability: ["Eternal Frost"] },
    appliesTo: "sanhua",
    modifiers: [{ class: "glacio", value: 0.4, concerto: 15, resonance: 7 }],
    duration: 5,
  },
  {
    id: "Ice Thorn",
    name: "Ice Thorn",
    source: "sanhua",
    classifications: ["glacio", "skill"],
    trigger: { ability: ["Freezing Thorns"] },
    appliesTo: "sanhua",
    modifiers: [{ class: "glacio", value: 0.3, resonance: 2 }],
    duration: 8,
  },
  {
    id: "Ice Glacier",
    name: "Ice Glacier",
    source: "sanhua",
    classifications: ["glacio", "skill"],
    trigger: { ability: ["Glacial Gaze"] },
    appliesTo: "sanhua",
    modifiers: [{ class: "glacio", value: 0.7, concerto: 15, resonance: 7 }],
    duration: 5,
  },
  {
    id: "Detonate",
    name: "Detonate",
    source: "sanhua",
    classifications: ["glacio", "skill"],
    trigger: { ability: ["Detonate"] },
    appliesTo: "sanhua",
    duration: 0,
  },
  {
    id: "Solitude's Embrace",
    name: "Solitude's Embrace",
    source: "sanhua",
    trigger: { ability: ["Frigid Light 5"] },
    appliesTo: "sanhua",
    modifiers: [{ class: "crit", value: 0.15 }],
    sequenceReq: 1,
    duration: 10,
  },
  // {
  //   id: "Anomalous Vision",
  //   name: "Anomalous Vision",
  //   type: "Buff",
  //   source: "sanhua",
  //   trigger: {},
  //   appliesTo: "sanhua",
  //   modifiers: [{ class: "all", value: 0.35 }],
  //   sequenceReq: 3,
  //   duration: 10,
  // },
  {
    id: "Blade Mastery",
    name: "Blade Mastery",
    source: "sanhua",
    trigger: { ability: ["Glacial Gaze"] },
    appliesTo: "sanhua",
    modifiers: [],
    sequenceReq: 4,
    duration: 5,
  },
  {
    id: "Blade Mastery (energy)",
    name: "Blade Mastery (energy)",
    source: "sanhua",
    trigger: { ability: ["Glacial Gaze"] },
    appliesTo: "sanhua",
    modifiers: [{ class: "resonance", value: 10 }],
    sequenceReq: 4,
    duration: 0,
  },
  {
    id: "Blade Mastery (bonus)",
    name: "Blade Mastery (bonus)",
    source: "sanhua",
    trigger: {
      ability: ["Detonate"],
      condition: ["Blade Mastery"],
    },
    appliesTo: "sanhua",
    modifiers: [{ class: "bonus", value: 1.2 }],
    sequenceReq: 4,
    duration: 0.1,
  },
  {
    id: "Unraveling Fate",
    name: "Unraveling Fate",
    source: "sanhua",
    trigger: { ability: ["Detonate"] },
    appliesTo: "sanhua",
    modifiers: [{ class: "critDmg", value: 1, concerto: 7.5 }], // 2 Detonate hits
    sequenceReq: 5,
    duration: 0.1,
  },
  {
    id: "Daybreak Radiance",
    name: "Daybreak Radiance",
    source: "sanhua",
    trigger: { ability: ["Detonate"] }, // TODO: actual proc logic
    appliesTo: "all",
    modifiers: [{ class: "atk", value: 0.1 }],
    stackLimit: 2,
    stackInterval: 0,
    sequenceReq: 6,
    duration: 20,
  },
]

export default sanhua
