import type { BuffDefinition } from "@/shared/types"

const shorekeeperBuffs: BuffDefinition[] = [
  {
    id: "Self Gravitation",
    name: "Self Gravitation",
    source: "shorekeeper",
    trigger: [
      {
        condition: "Outer Stellarealm",
      },
    ],
    appliesTo: "shorekeeper",
    modifiers: [{ class: "er", value: 0.1 }],
    duration: 30,
  },
  // {
  //   id: "Self Gravitation (rover)",
  //   name: "Self Gravitation (rover)",
  //   source: "shorekeeper",
  //   trigger: {
  //     condition: ["Outer Stellarealm", " Inner Stellarealm", "Supernal Stellarealm"],
  //   },
  //   appliesTo: "rover",
  //   modifiers: [{ class: "er", value: 0.1 }],
  //   duration: 0,
  // },
  {
    id: "Binary Butterfly",
    name: "Binary Butterfly",
    source: "shorekeeper",
    trigger: [{ ability: "Binary Butterfly" }],
    appliesTo: "all",
    modifiers: [{ class: "allDeep", value: 0.15 }],
    duration: 30,
  },
  {
    id: "Outer Stellarealm",
    name: "Outer Stellarealm",
    source: "shorekeeper",
    trigger: [{ ability: "End Loop" }],
    appliesTo: "all",
    modifiers: [
      {
        class: "heal",
        frame: 180,
        value: 0.0239,
        flat: 438,
        type: "heal",
      },
      {
        class: "heal",
        frame: 360,
        value: 0.0239,
        flat: 438,
        type: "heal",
      },
      {
        class: "heal",
        frame: 540,
        value: 0.0239,
        flat: 438,
        type: "heal",
      },
      {
        class: "heal",
        frame: 720,
        value: 0.0239,
        flat: 438,
        type: "heal",
      },
      {
        class: "heal",
        frame: 900,
        value: 0.0239,
        flat: 438,
        type: "heal",
      },
      {
        class: "heal",
        frame: 1080,
        value: 0.0239,
        flat: 438,
        type: "heal",
      },
      {
        class: "heal",
        frame: 1260,
        value: 0.0239,
        flat: 438,
        type: "heal",
      },
      {
        class: "heal",
        frame: 1440,
        value: 0.0239,
        flat: 438,
        type: "heal",
      },
      {
        class: "heal",
        frame: 1620,
        value: 0.0239,
        flat: 438,
        type: "heal",
      },
      {
        class: "heal",
        frame: 1800,
        value: 0.0239,
        flat: 438,
        type: "heal",
      },
    ],
    duration: 30,
  },
  {
    id: "Inner Stellarealm",
    name: "Inner Stellarealm",
    source: "shorekeeper",
    trigger: [{ category: "intro", condition: "Outer Stellarealm" }],
    appliesTo: "all",
    modifiers: [
      { class: "crit", statReq: "er", stepValue: 0.002, value: 0.0001 },
    ],
    stackLimit: 1250,
    stackInterval: 0,
    duration: 30,
  },
  {
    id: "Supernal Stellarealm",
    name: "Supernal Stellarealm",
    source: "shorekeeper",
    trigger: [{ category: "intro", condition: "Inner Stellarealm" }],
    appliesTo: "all",
    modifiers: [
      { class: "critDmg", statReq: "er", stepValue: 0.001, value: 0.0001 },
    ],
    stackLimit: 2500,
    stackInterval: 0,
    duration: 30,
  },
]

export default shorekeeperBuffs
