import type { BuffObject } from "@/constants/types"

export const buffs: Record<string, BuffObject[]> = {
  encore: [
    {
      name: "Angry Cosmos",
      type: "Buff",
      source: "encore",
      triggeredBy: ["Cosmos Rave"],
      appliesTo: "encore",
      modifier: ["all"],
      value: 0.1,
      duration: 10,
    },
    {
      name: "Woolies Cheer Dance",
      type: "Buff",
      source: "encore",
      triggeredBy: ["Flaming Woolies", "Cosmos Rampage"],
      appliesTo: "encore",
      modifier: ["fusion"],
      value: 0.1,
      duration: 10,
    },
  ],
  sanhua: [
    {
      name: "Silversnow",
      type: "BuffNext",
      source: "sanhua",
      triggeredBy: ["Silversnow"],
      appliesTo: "Next",
      modifier: ["baDeep"],
      value: 0.38,
      duration: 14,
    },

    {
      name: "Ice Prism",
      type: "Damage",
      source: "sanhua",
      triggeredBy: ["Eternal Frost"],
      appliesTo: "sanhua",
      modifier: [],
      consumedBy: ["Detonate"],
      value: 0.4,
      duration: 5,
      concerto: 15,
      resonance: 7,
    },
    {
      name: "Ice Thorn",
      type: "Damage",
      source: "sanhua",
      triggeredBy: ["Freezing Thorns"],
      appliesTo: "sanhua",
      modifier: [],
      consumedBy: ["Detonate"],
      value: 0.3,
      duration: 8,
      resonance: 2,
    },
    {
      name: "Ice Glacier",
      type: "Damage",
      source: "sanhua",
      triggeredBy: ["Glacial Gaze"],
      appliesTo: "sanhua",
      modifier: [],
      consumedBy: ["Detonate"],
      value: 0.7,
      duration: 5,
      concerto: 15,
      resonance: 7,
    },
  ],
}
