import type { BuffObject } from "@/constants/types"

export const buffs: Record<string, BuffObject[]> = {
  encore: [
    {
      id: "Angry Cosmos",
      name: "Angry Cosmos",
      type: "Buff",
      source: "encore",
      triggeredBy: ["Cosmos Rave"],
      appliesTo: "encore",
      modifiers: [{ class: "all", value: 0.1 }],
      duration: 10,
    },
    {
      id: "Woolies Cheer Dance",
      name: "Woolies Cheer Dance",
      type: "Buff",
      source: "encore",
      triggeredBy: ["Flaming Woolies", "Cosmos Rampage"],
      appliesTo: "encore",
      modifiers: [{ class: "fusion", value: 0.1 }],
      duration: 10,
    },
    {
      id: "Cosmos Rave",
      name: "Cosmos Rave",
      type: "Buff",
      source: "encore",
      triggeredBy: ["Cosmos Rave"],
      appliesTo: "encore",
      modifiers: [],
      duration: 10,
    },
    {
      id: "Wooly's Fairy Tale",
      name: "Wooly's Fairy Tale",
      type: "BuffStacking",
      source: "encore",
      triggeredBy: ["basic"],
      appliesTo: "encore",
      modifiers: [{ class: "fusion", value: 0.03 }],
      stackLimit: 4,
      sequenceReq: 1,
      duration: 6,
    },
    {
      id: "Sheep-counting Lullaby",
      name: "Sheep-counting Lullaby",
      type: "DCondFlat",
      source: "encore",
      triggeredBy: ["basic"],
      appliesTo: "encore",
      modifiers: [{ class: "resonance", value: 10 }],
      cooldown: 10,
      sequenceReq: 2,
      duration: 0,
    },
  ],

  sanhua: [
    {
      id: "Silversnow",
      name: "Silversnow",
      type: "BuffNext",
      source: "sanhua",
      triggeredBy: ["Silversnow"],
      appliesTo: "Next",
      modifiers: [{ class: "baDeep", value: 0.38 }],
      duration: 14,
    },

    {
      id: "Ice Prism",
      name: "Ice Prism",
      type: "Damage",
      source: "sanhua",
      classifications: ["glacio", "skill"],
      triggeredBy: ["Eternal Frost"],
      appliesTo: "sanhua",
      modifiers: [{ class: "glacio", value: 0.4, concerto: 15, resonance: 7 }],
      consumedBy: ["Detonate"],
      duration: 5,
    },
    {
      id: "Ice Thorn",
      name: "Ice Thorn",
      type: "Damage",
      source: "sanhua",
      classifications: ["glacio", "skill"],
      triggeredBy: ["Freezing Thorns"],
      appliesTo: "sanhua",
      modifiers: [{ class: "glacio", value: 0.3, resonance: 2 }],
      consumedBy: ["Detonate"],
      duration: 8,
    },
    {
      id: "Ice Glacier",
      name: "Ice Glacier",
      type: "Damage",
      source: "sanhua",
      classifications: ["glacio", "skill"],
      triggeredBy: ["Glacial Gaze"],
      appliesTo: "sanhua",
      modifiers: [{ class: "glacio", value: 0.7, concerto: 15, resonance: 7 }],
      consumedBy: ["Detonate"],
      duration: 5,
    },
  ],
  shorekeeper: [
    {
      id: "Self Gravitation",
      name: "Self Gravitation",
      type: "BuffOffField",
      source: "shorekeeper",
      triggeredBy: ["Stellarealm", "off-field"],
      appliesTo: "shorekeeper",
      modifiers: [{ class: "er", value: 0.1 }],
      duration: 25,
    },
  ],
}
